
/*
 * File automatically generated by obj2c
 */

const float floor_flatVertexes[][3] = {
	{1.250005f, -2.067688f, 1.250004f},
	{1.250005f, -2.067688f, -1.250004f},
	{-1.250007f, -2.067688f, -1.250004f},
	{-1.250003f, -2.067688f, 1.250004f}
};
const int floor_flatVertexesCount = 4;

const float floor_flatTexCoords[][2] = {
	{1.0f, 0.0f},
	{1.0f, 1.0f},
	{0.0f, 1.0f},
	{0.0f, 0.0f}
};
const int floor_flatTexCoordsCount = 4;

const unsigned short floor_flatIndexes[] = {
	0,
	1,
	2,
	3,
	0,
	2,
	3,
	0,
	2
};
const int floor_flatIndexesCount = 9;

